#
# Makefile.mingw
#
# Description: Makefile for switchspell plugin.
#

ENCHANT_TOP = $(PIDGIN_TREE_TOP)/../win32-dev/enchant_1.5.0-2_win32
GTKSPELL_TOP = $(PIDGIN_TREE_TOP)/../win32-dev/gtkspell-2.0.16
PP_TOP :=		..

PP = switchspell

include $(PP_TOP)/win_pp.mak

INCLUDE_PATHS += \
	-I$(GTKSPELL_TOP)/include/gtkspell-2.0 \
	-I$(ENCHANT_TOP)/include/enchant

LIB_PATHS += \
	-L$(GTKSPELL_TOP)/lib \
	-L$(ENCHANT_TOP)/lib

PLUGIN_LIBS += \
	-llibgtkspell \
	-llibenchant

