#
# Makefile.mingw
#
# Description: Makefile for switchspell plugin.
#

ASPELL_TOP = $(PIDGIN_TREE_TOP)/../win32-dev/aspell-dev-0-50-3-3
GTKSPELL_TOP = $(PIDGIN_TREE_TOP)/../win32-dev/gtkspell-2.0.6
PP_TOP :=		..

PP = switchspell

include $(PP_TOP)/win_pp.mak

INCLUDE_PATHS += \
	-I$(GTKSPELL_TOP) \
	-I$(ASPELL_TOP)/include

LIB_PATHS += \
	-L$(GTKSPELL_TOP)/gtkspell \
	-L$(ASPELL_TOP)/lib

PLUGIN_LIBS += \
	-lgtkspell \
	-laspell-15

