#
# Makefile.mingw
#
# Description: Makefile for irssi plugin.
#

GPP_TOP :=		..

GPP = irssi

GPP_SRC := \
	datechange.c \
	layout.c \
	lastlog.c \
	textfmt.c \
	window.c \
	irssi.c

include $(GPP_TOP)/win_gpp.mak

