#!/bin/sh

set -e

if [ -f ../plugin_pack.py ] ; then
	echo "*** Please make sure your debian directory is under the top_srcdir of a" >&2
	echo "*** plugin pack release directory!" >&2

	exit 1
fi

OUTPUT=`mktemp control-XXXX`

trap "rm -f ${OUTPUT}" 0 1 2 3 15

# output the source package, and the header of the pidgin-plugin-pack package
cat << EOF >> ${OUTPUT}
Source: purple-plugin-pack
Section: net
Priority: optional
Maintainer: Benjamin Seidenberg <benjamin@debian.org>
Build-Depends: debhelper (>= 5), pidgin-dev, pkg-config, libgtk2.0-dev, libglib2.0-dev, libxml-parser-pe
Standards-Version: 3.8.0

Package: pidgin-plugin-pack
Architecture: any
Depends: \${shlibs:Depends}, \${misc:Depends}
Enhances: pidgin, xmms
EOF

# output the details for pidgin-plugin-pack
python ../plugin_pack.py debian_description

# output the transient packages
cat << EOF >> ${OUTPUT}

Package: gaim-irchelper
Architecture: all
Depends: pidgin-plugin-pack
Description: IRC extensions for Pidgin (dummy transitional package)
 This plugin enhances the usability of the IRC protocol in Pidgin.
 .
 This dummy package depends upon pidgin-plugin-pack, which provides
 the IRC helper starting with the Debian release codename Lenny. It
 can safely be removed after the upgrade to Lenny is complete.

EOF

