#!/bin/sh

set -e

if [ ! -f ../plugin_pack.py ] ; then
	echo "*** Please make sure your debian directory is under the top_srcdir of a" >&2
	echo "*** plugin pack release directory!" >&2

	exit 1
fi

OUTPUT=`mktemp control-XXXX`

trap "rm -f ${OUTPUT}" 0 1 2 3 15

# output the source package, and the header of the pidgin-plugin-pack package
cat << EOF >> ${OUTPUT}
Source: purple-plugin-pack
Section: net
Priority: optional
Maintainer: John Bailey <rekkanoryo@rekkanoryo.org>
Build-Depends: debhelper (>= 5), pidgin-dev, pkg-config, libgtk2.0-dev, libglib2.0-dev, libxml-parser-perl, libenchant-dev, libgtkspell-dev, python
Standards-Version: 3.8.1

Package: pidgin-plugin-pack
Architecture: any
Depends: \${shlibs:Depends}, \${misc:Depends}
Enhances: pidgin, xmms
EOF

# output the details for pidgin-plugin-pack
python ../plugin_pack.py debian_description >> ${OUTPUT}

# now move the new control file in place
mv ${OUTPUT} control
