#
# Makefile.mingw
#
# Description: Makefile for okcupid plugin.
#

JSON_GLIB_TOP = $(PIDGIN_TREE_TOP)/../win32-dev/libjson-glib
PP_TOP :=		..

PP = okcupid

PP_SRC := \
	okcupid.c \
	okc_blist.c \
	okc_connection.c \
	okc_messages.c

include $(PP_TOP)/win_pp.mak

INCLUDE_PATHS += \
	-I$(JSON_GLIB_TOP)/include/json-glib-1.0

LIB_PATHS += \
	-L$(JSON_GLIB_TOP)/lib

PLUGIN_LIBS += \
	-ljson-glib-1.0 \
	-lz
