#
# Makefile.mingw
#
# Description: Makefile for listhandler plugin.
#

PP_TOP :=		..

PP = listhandler


PP_SRC := \
	aim_blt_files.c \
	alias_xml_files.c \
	gen_xml_files.c \
	lh_util.c \
	listhandler.c \
	migrate.c \
	purple_blist_xml.c

include $(PP_TOP)/win_pp.mak

